- name: Deploy Java App to Remote Tomcat
  hosts: remote_server
  become: no  # Disable sudo globally
  vars:
    repo_url: "git@github.com:thinkvalleyacademy/user-management.git"
    branch_name: "main_v1_dev_release"
    local_build_dir: "user-management"
    war_file: "user-management/target/user-management.war"
    remote_deploy_dir: "/opt/tomcat/webapps"
    tomcat_service: "tomcat"

  tasks:
    - name: Ensure local build directory exists
      delegate_to: localhost
      file:
        path: "{{ local_build_dir }}"
        state: directory

    - name: Clone the GitHub repository (locally)
      delegate_to: localhost
      environment:
        GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ local_build_dir }}"
        version: "{{ branch_name }}"
        force: yes

    - name: Build Java project using Maven (locally)
      delegate_to: localhost
      shell: |
        cd {{ local_build_dir }}
        mvn clean package
      args:
        creates: "{{ war_file }}"

    - name: Copy WAR file to remote server
      become: yes  # Elevate privileges only for this task
      copy:
        src: "{{ war_file }}"
        dest: "{{ remote_deploy_dir }}/user-management.war"
        mode: '0644'

    - name: Restart Tomcat service
      become: yes  # Elevate privileges only for this task
      systemd:
        name: "{{ tomcat_service }}"
        state: restarted

