- name: Deploy React App to Remote Nginx
  hosts: remote_server
  become: yes  # Run tasks with sudo privileges when needed
  vars:
    repo_url: "git@github.com:thinkvalleyacademy/tva-dashboard-ui.git"
    branch_name: "main_v1_dev_release"
    local_build_dir: "tva-dashboard-ui"
    build_output: "tva-dashboard-ui/build"
    archive_name: "react-app.tar.gz"
    remote_deploy_dir: "/var/www/react-app"
    nginx_service: "nginx"

  tasks:
    - name: Ensure local build directory exists
      delegate_to: localhost
      file:
        path: "{{ local_build_dir }}"
        state: directory

    - name: Clone the React repository (locally)
      delegate_to: localhost
      environment:
        GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ local_build_dir }}"
        version: "{{ branch_name }}"
        force: yes

    - name: Install dependencies and build React app (locally)
      delegate_to: localhost
      shell: |
        cd {{ local_build_dir }}
        npm install
        npm run build

    - name: Archive the React build folder (locally)
      delegate_to: localhost
      archive:
        path: "{{ build_output }}"
        dest: "{{ archive_name }}"
        format: gz

    - name: Copy the compressed archive to the remote server
      copy:
        src: "{{ archive_name }}"
        dest: "/tmp/{{ archive_name }}"
        mode: '0644'

    - name: Ensure remote deploy directory exists
      file:
        path: "{{ remote_deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Extract the React build archive on the remote server
      unarchive:
        src: "/tmp/{{ archive_name }}"
        dest: "{{ remote_deploy_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]  # Remove the 'build' folder wrapper

    - name: Set correct permissions on deployed files
      file:
        path: "{{ remote_deploy_dir }}"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Restart Nginx to apply changes
      systemd:
        name: "{{ nginx_service }}"
        state: restarted

