- name: Install Docker, Docker Compose, and Nginx
  hosts: remote_server
  become: yes  # Run as sudo
  tasks:

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install required packages for Docker
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
        state: present
      when: docker_installed.failed

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      when: docker_installed.failed

    - name: Add Docker repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      when: docker_installed.failed

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: docker_installed.failed

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'

    - name: Check if Nginx is installed
      command: nginx -v
      register: nginx_installed
      ignore_errors: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: nginx_installed.failed

    - name: Ensure Nginx service is started
      systemd:
        name: nginx
        state: started
        enabled: yes

