- name: Install Docker on Remote Server
  hosts: remote_server
  become: yes  # Run as sudo

  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker configuration directory exists
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker DNS settings
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "dns": ["8.8.8.8", "1.1.1.1"]
          }
        mode: '0644'

    - name: Restart Docker to apply DNS settings
      service:
        name: docker
        state: restarted
        enabled: yes

